### ISSUE TITLE
Changes to support spec `v0.6.0` compliance

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk#177]
## Implement specification v0.6.0 changes

See [changes since last release](https://github.com/open-feature/spec/compare/v0.5.2...v0.6.0).

**_Please note there's no need to complete all these tasks in a single PR (in fact, that's not recommended)._**

### Functional requirements:

- [x] implement flag metadata: https://github.com/open-feature/spec/commit/74c373e089ad77bf8cac84f3d93c00c945ff3a8a
- [x] #183
- [x] #184
- [x] #186

### Non-functional requirements:

- [x] add relevant tests
- [x] add examples and documentation, see template README
- [x] update specification badge to `v0.6.0`: [![Specification](https://img.shields.io/static/v1?label=Specification&message=v0.6.0&color=yellow)](https://github.com/open-feature/spec/tree/v0.6.0)

### Keep in mind:

- backwards compatibility is _highly encouraged_
  - take every precaution to ensure existing code written by _application authors_ and existing providers implementations, do not break
- it's recommended these features are released together

**Comment by Kavindu-Dodan** [comment]
I will continue to work on **implement initialization/shutdown: https://github.com/open-feature/spec/commit/a4ffec3d4416b8ad6d12d1ebfa2faf81ad153f65**

**Comment by toddbaert** [comment]
@Kavindu-Dodan I've created sub-issues and assigned to you. Thanks!

**Comment by Kavindu-Dodan** [comment]
All functional and non-functional goals have been met with the linked PRs.
