### ISSUE TITLE
Conform to spec `v0.7.0`

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk#217]
Update the SDK to be compliant with `v0.7.0`.

- [x] ensure compliance with all point in `v0.7.0` (see [here](https://github.com/open-feature/spec/releases/tag/v0.7.0) for list of changes) 
  - [x] #220
  - [x] add new STALE provider state
  - [x] add `provider name` to `event details`
- [x] implement relevant tests
- [x] update spec badge in README.md

> [!NOTE]
> the Go SDK may already implement some of these - for instance I believe the provider-name is already present in event details.

**Comment by craigpastro** [comment]
Hi @toddbaert 👋 

I think the Go SDK has already implemented all of these.

1. When https://github.com/open-feature/go-sdk/blob/d850ebc5c831ccee5edd490e3c2f019e2188b4ad/pkg/openfeature/event_executor.go#L80 is called, the last line is `e.emitOnRegistration` which "fulfils the spec requirement to fire ready events if associated provider is ready".
2. https://github.com/open-feature/go-sdk/blob/d850ebc5c831ccee5edd490e3c2f019e2188b4ad/pkg/openfeature/provider.go#L32
3. https://github.com/open-feature/go-sdk/blob/d850ebc5c831ccee5edd490e3c2f019e2188b4ad/pkg/openfeature/provider.go#L111 and it seems to be populated on events in `event_executor.go`.

**Comment by toddbaert** [comment]
Thanks @craigpastro ! I think that's all correct except this point: 

>  event handlers should run immediately if the associated provider is in the state associated with that handler already

I think currently the handler runs immediately only in the ready state - but this needs to change to be the case for all states, ie: if the provider is in STALE state, and you add a STALE handler, then it should run immediately, same with ERROR.

**Comment by craigpastro** [comment]
> If you agree, and that makes sense to you, I can create an issue for that and assign it to your if you're interested.

I think this makes sense. Sure, I can give it a shot. Thanks!

**Comment by craigpastro** [comment]
I had a go at resolving #220 in #221. I made a mistake earlier in the sense that `add new STALE provider state` was not actually done, and I added it in the PR. Thanks!

**Comment by craigpastro** [comment]
Is the only thing left for this issue to bump the version for the spec badge? Do you think the tests are enough?

**Comment by toddbaert** [comment]
> Is the only thing left for this issue to bump the version for the spec badge? Do you think the tests are enough? In any case, I'll create the PR to bump the version so we're ready to go!

I think that's all that's needed.
