### ISSUE TITLE
[FEATURE] Follow up for 227

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/go-sdk#234]
### Requirements

This is to track follow-up tasks of the change proposed through https://github.com/open-feature/go-sdk/issues/227 

Once https://github.com/open-feature/go-sdk/pull/232 is merged fixing #227, we must perform the following tasks,

- [x] Update the documentation examples to reflect the packaging change
- [x] Update go-sdk-contrib repository references

**Comment by beeme1mr** [comment]
The readme should be updated before the next release.
