### ISSUE TITLE
[FEATURE] Blocking provider mutator

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk#240]
### Requirements

As is recommended by the spec, we should add a blocking version of setProvider. This would wait for the provider to be initialized before it returns. It should be named in such a way that its blocking behavior is obvious, and should be documented appropriately. The README should be update to include it (close to the start) and highlight how it behaves differently from `setProvider`.

See a [PR for a similar feature in Java](https://github.com/open-feature/java-sdk/pull/563).

Please be sure to add tests!

Relates to: https://github.com/open-feature/go-sdk/issues/238

**Comment by Kavindu-Dodan** [comment]
I will take over this as the current open PR #244 is not maintained for almost two weeks.
