### ISSUE TITLE
[FEATURE] Expose domain specific provider metadata getter

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/go-sdk#247]
### Requirements

Requirement 1.1.5 specify that,

> The API MUST provide a function for retrieving the metadata field of the configured provider.

With upcoming enhancements to requirement [^1], there's the need to expose the same for domain-specific providers. 

> It must be possible to access provider metadata using a `domain`.

**AC**

Introduce a domain-specific provider metadata getter to Go-SDK

[^1]: https://github.com/open-feature/spec/pull/229

**Comment by beeme1mr** [comment]
Relates to #257
