### ISSUE TITLE
[FEATURE] Move to log/slog logging 

### ISSUE THREAD

**Issue by cndoit18** [open-feature/go-sdk#260]
### Requirements

Now that structured logging has landed in the standard library, we can shed an external dependency and just use log/slog.

**Comment by Kavindu-Dodan** [comment]
@cndoit18 thank you for bringing this up. Currently, we use logr [1], and once we upgrade our Go version to 1.21, we could consider migrating/using the standard logger. 

I will create a follow-up issue for 1.21 upgrade once we merge #255 [2]


[1] - https://github.com/open-feature/go-sdk?tab=readme-ov-file#logging
[2] - https://github.com/open-feature/go-sdk/pull/255

**Comment by Kavindu-Dodan** [comment]
Added breaking change tag as adoption of slog will break backward compatibility for older go versions. When implementing, we should consider interoperability with logr [1] and see if there're any API changes. 

[1] - https://github.com/go-logr/logr?tab=readme-ov-file#slog-interoperability

**Comment by liran2000** [comment]
Can be closed via #289
