### ISSUE TITLE
[BUG] Race condition when testing with memprovider

### ISSUE THREAD

**Issue by natenho** [open-feature/go-sdk#293]
Hi! I'm not really sure if this can be considered a bug, but someone could be led to test the code this way.

Consider that I'm testing code and I want to cover both scenarios of a feature flag being enabled and disabled. So we don't want to rely on actual providers, just a stub. The memprovider is the way to go:

```
func TestParallelSingletonUsage(t *testing.T) {
	t.Parallel()

	type fields struct {
		givenFlagValue bool
	}

	tests := map[string]struct {
		fields fields
		want   bool
	}{
		"test when flag is true": {
			fields: fields{givenFlagValue: true},
			want:   true,
		},
		"test when flag is false": {
			fields: fields{givenFlagValue: false},
			want:   false,
		},
	}

	for name, tt := range tests {
		tt := tt
		name := name
		t.Run(name, func(t *testing.T) {
			t.Parallel()

			err := openfeature.GetApiInstance().SetProvider( // Here we have a race condition! We need to set the provider in parallel to ensure the test runs under the expected condition
				memprovider.NewInMemoryProvider(
					map[string]memprovider.InMemoryFlag{
						"some_cool_feature": {
							State:          memprovider.Enabled,
							DefaultVariant: "variant_1",
							Variants: map[string]any{
								"variant_1": tt.fields.givenFlagValue, // Make sure the provider always returns the value given by the test case
							},
							ContextEvaluator: nil,
						},
					},
				))

			require.NoError(t, err)

			got := theActualCodeUnderTest()

			require.Equal(t, tt.want, got, "uh oh, value is not as expected")
		})
	}
}

func theActualCodeUnderTest() bool {
	return openfeature.GetApiInstance().
		GetClient().
		Boolean(context.Background(), "some_cool_feature", false, openfeature.EvaluationContext{})
}

```

Running a single test it is not a issue:

```
$ go test -run ^TestParallelSingletonUsage$ local/goff-tests -count=1
ok      local/goff-tests        0.005s
```

Running more parallel tests, you can start to see some unpredictable results:
```
$ go test -run ^TestParallelSingletonUsage$ local/goff-tests -count=20
--- FAIL: TestParallelSingletonUsage (0.00s)
    --- FAIL: TestParallelSingletonUsage/test_when_flag_is_true (0.00s)
        parallel_test.go:57: 
                Error Trace:    /home/renato_lima/go/src/local/goff-tests/parallel_test.go:57
                Error:          Not equal: 
                                expected: true
                                actual  : false
                Test:           TestParallelSingletonUsage/test_when_flag_is_true
                Messages:       uh oh, value is not as expected
--- FAIL: TestParallelSingletonUsage (0.00s)
    --- FAIL: TestParallelSingletonUsage/test_when_flag_is_true (0.00s)
        parallel_test.go:57: 
                Error Trace:    /home/renato_lima/go/src/local/goff-tests/parallel_test.go:57
                Error:          Not equal: 
                                expected: true
                                actual  : false
                Test:           TestParallelSingletonUsage/test_when_flag_is_true
                Messages:       uh oh, value is not as expected
FAIL
FAIL    local/goff-tests        0.010s
FAIL
```

Any suggestion on how to avoid that only using the sdk is appreciated ;).

**Comment by guidobrei** [comment]
This is "intended" behavior. 
Only one _default provider_ can be set in the API ([see specification](https://openfeature.dev/specification/sections/flag-evaluation#setting-a-provider)). 
If you want to use multiple providers as in your code sample, you can make use of the [domain concept](https://openfeature.dev/specification/glossary#domain). Here you can isolate providers into domains. 

I'm not too deep into the Go SDK, but I think this is realized through the `SetNamedProvider()` and `GetNamedClient()` functions.

**Comment by natenho** [comment]
Hello Guido,

I'm actually not intended to use multiple providers. My intent is to ensure
each test run under a specific feature flag variation.

Do you have any suggestion on how to do that?

**Comment by aepfli** [comment]
Hey, I am evaluating our Java approach to see if it is feasible to implement something similar in Golang.

What we are doing is a little bit hacky, but we have not yet devised another solution.
We do have one TestProvider, in which we maintain a map. This map has the test name as a key and its own in-memory provider as a value.
On each test run, we're storing the test name in a thread-local (important, as we can't pass this information on in another way) and, based on this information, delegate to the corresponding provider based on the map.

This approach works because we can utilize many Java specifics (e.g., this is our own test extension). But I need to evaluate whether something like this would be feasible within Golang, and I will get back to you.

**Comment by aepfli** [comment]
I now need feedback on this idea, but what if we generate a TestProvider that prevents parallel execution when used with a Mutex (kudos to @toddbaert for this idea)? 

Normally, test execution time is not a critical factor, and this seems like a feasible tradeoff to prevent race conditions. However, I am not really familiar with Golang enough to evaluate this idea properly or see all possible side effects. Wdyt? Could this be a feasible solution?

I tried to do some research to mimic our Java approach, but passing on the test name or any other indicator to our evaluation without a race condition seems to be hard. There would be the Context we can use, but this would require all our users to actually accept a context on each method under test (which is, in my opinion, not feasible; it seems like writing production code purely for testing).

**Comment by toddbaert** [comment]
> I now need feedback on this idea, but what if we generate a TestProvider that prevents parallel execution when used with a Mutex (kudos to [@toddbaert](https://github.com/toddbaert) for this idea)?
> 
> Normally, test execution time is not a critical factor, and this seems like a feasible tradeoff to prevent race conditions. However, I am not really familiar with Golang enough to evaluate this idea properly or see all possible side effects. Wdyt? Could this be a feasible solution?
> 
> I tried to do some research to mimic our Java approach, but passing on the test name or any other indicator to our evaluation without a race condition seems to be hard. There would be the Context we can use, but this would require all our users to actually accept a context on each method under test (which is, in my opinion, not feasible; it seems like writing production code purely for testing).

Ya my TLDR for how this might work is you have a utility of some kind that you open and close (probably with a defer) which will prevent interleaving `setProvider` calls on the singleton until it's closed; it could even be build into a special test provider which holds a shared lock, and which encapsulates the memory provider; this could prevent tests from interleaving, but the locking could hurt performance a bit. It may be the beset option though.

**Comment by warber** [comment]
I think I agree with @toddbaert 
So, this is quite easy to achieve, with e.g. a custom `TestProvider` right?

```go
var TP = TestingProvider{}

type TestingProvider struct {
	memprovider.InMemoryProvider
	sync.Mutex
}

func (t *TestingProvider) Wait() {
	t.Lock()
}

func (t *TestingProvider) Cont() {
	t.Unlock()
}

func (t *TestingProvider) SetProvider(provider memprovider.InMemoryProvider) {
	t.InMemoryProvider = provider
	openfeature.GetApiInstance().SetProvider(t)
}
```

And using the locking methods in the test:

```go
func TestParallelSingletonUsage(t *testing.T) {
	t.Parallel()

	type fields struct {
		givenFlagValue bool
	}

	tests := map[string]struct {
		fields fields
		want   bool
	}{
		"test when flag is true": {
			fields: fields{givenFlagValue: true},
			want:   true,
		},
		"test when flag is false": {
			fields: fields{givenFlagValue: false},
			want:   false,
		},
	}

	for name, tt := range tests {
		tt := tt
		name := name
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			TP.Wait() //<<<<<<<<<<<<
			TP.SetProvider(memprovider.NewInMemoryProvider(
				map[string]memprovider.InMemoryFlag{
					"some_cool_feature": {
						State:          memprovider.Enabled,
						DefaultVariant: "variant_1",
						Variants: map[string]any{
							"variant_1": tt.fields.givenFlagValue,
						},
						ContextEvaluator: nil,
					},
				},
			))
			got := theActualCodeUnderTest()
			TP.Cont() //<<<<<<<<<<
			require.Equal(t, tt.want, got, "uh oh, value is not as expected")
		})
	}
}
```

However, this essentially "reverts" the effect of `t.Parallel()`, which raises the question: "why not simply avoid running these tests in parallel in the first place?" :D

**Comment by warber** [comment]
@natenho I’ve submitted a draft PR with a potential solution for this (#295). I’d love to hear your thoughts and see if it meets your needs.
