### ISSUE TITLE
Domain-scoped clients are not usable initially

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk#310]
Domain scoped clients should default to the default provider, which is always usable (no-ops) but doesn't not emit READY events.

This seems to be a regression around our new stateless provider functionality implemented in https://github.com/open-feature/go-sdk/pull/299

# Background

              Reported in Slack: https://cloud-native.slack.com/archives/C06HAN9KP9Q/p1732715248777879?thread_ts=1732656743.817279&cid=C06HAN9KP9Q

From Roman:
```
It has a breaking change from client usage. Before client := of.NewClient("app")  fallbacks to default provider, but now it says that provider not yet initialized.
```

_Originally posted by @beeme1mr in https://github.com/open-feature/go-sdk/pull/296#pullrequestreview-2465098493_

**Comment by erka** [comment]
Great work @warber !

Could we close this?  Github haven't done it automatically

**Comment by beeme1mr** [comment]
Resolved by https://github.com/open-feature/go-sdk/pull/309
