### ISSUE TITLE
Add OpenSSF Best Practices Badge

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/go-sdk#37]
The CNCF require that we start the process of achieving a OpenSSF best practices badge.

https://bestpractices.coreinfrastructure.org/en

The tool scans a repo and provides a report of the items that are incomplete or missing.

**Comment by beeme1mr** [comment]
The Java SDK recently achieved a 100%.

https://bestpractices.coreinfrastructure.org/en/projects/6241

**Comment by toddbaert** [comment]
> The Java SDK recently achieved a 100%.
> 
> https://bestpractices.coreinfrastructure.org/en/projects/6241

swag

**Comment by davejohnston** [comment]
Challenge accepted.  I'll try and spend some time this week going through that list before submitting the project.  @beeme1mr  I assume we can re-submit as many times as we address issues?

**Comment by skyerus** [comment]
PR for contributing doc: https://github.com/open-feature/go-sdk/pull/104
