### ISSUE TITLE
[FEATURE] Review and simplify application author facing APIs if possible

### ISSUE THREAD

**Issue by skyerus** [open-feature/go-sdk#62]
### Requirements

While other breaking changes are taking place (https://github.com/open-feature/golang-sdk/issues/56 & https://github.com/open-feature/golang-sdk/issues/57) it's a good time to review whether any quality of life improvements can be made to application author facing APIs.

**Comment by skyerus** [comment]
I've opened PRs for two potential improvements to the client API, we need to decide which approach is preferable, or perhaps some combination of the two.

https://github.com/open-feature/golang-sdk/pull/63
This separates the flag calls into two, the first is a simplified call without the `EvaluationOptions` parameter, the second is as before. This retains the enforcement of including the `EvaluationContext` in all flag resolution calls.

https://github.com/open-feature/golang-sdk/pull/64
This also separates the flag calls into two, both of which now have `EvaluationOptions` as a variadic parameter in order to simulate an "optional" parameter.
The original is now a simplified call without the `EvaluationContext` parameter with the addition of a new `WithContext` func that includes the `EvaluationContext` parameter.

@james-milligan @beeme1mr @toddbaert

**Comment by james-milligan** [comment]
I prefer the variadic approach, it makes for a cleaner interface

**Comment by skyerus** [comment]
@toddbaert does your approval of https://github.com/open-feature/golang-sdk/pull/63 mean that's your preferred approach? James & I prefer the other approach

**Comment by skyerus** [comment]
We settled on a middle ground approach of retaining the `EvaluationContext` as a first class parameter and making the `EvaluationOptions` variadic

**Comment by toddbaert** [comment]
@victorkt @skyerus ... what's not to like about this option?! Makes sense to me.
