### ISSUE TITLE
Add `context.Context` as first parameters to client/provider calls

### ISSUE THREAD

**Issue by markphelps** [open-feature/go-sdk#72]
Apologies if this has already been discussed.

I may be missing something, but is it possible to add Go's [context.Context](https://pkg.go.dev/context) as a first parameter to all client/provider methods (interface definitions)?

Ex: https://github.com/open-feature/go-sdk/blob/d1d0b5e95eaf8f7e8fff5d0b0a59e8af12c75dc2/pkg/openfeature/client.go#L16

would become something like:

```go
BooleanValue(ctx context.Context, flag string, defaultValue bool, evalCtx EvaluationContext, options EvaluationOptions) (bool, error)
```

It seems as a user of this SDK that I would want to be able to use [context](https://pkg.go.dev/context) to pass request timeouts upstream to the provider (ie: in case request to provider is taking too long to return, error which would return the 'default' value).

Is this meant to be done via a `Hook` per request? If so would it be possible to document this usage? 

Although it still seems that passing `context.Context` as a first class (first) parameter would be ideal IMO since it is a Go convention.

**Comment by skyerus** [comment]
I agree that this would be beneficial and is definitely the idiomatic approach, I'm all for making this change.

As this would be another breaking change, we ought to decide and commit sooner rather than later.

cc @james-milligan @beeme1mr @toddbaert

**Comment by james-milligan** [comment]
i agree with @skyerus, context would be a great addition to the sdk

**Comment by markphelps** [comment]
Awesome. I'd be happy to create a PR, if nothing else to at least show what it would look like

**Comment by markphelps** [comment]
Amazing, thanks for the quick turn around!

**Comment by beeme1mr** [comment]
Hey @markphelps, thanks again for your suggestion. It will be included in an [upcoming release](https://github.com/open-feature/go-sdk/pull/78).
